server:
  port: 8080

logging:
  config=classpath: logback.xml

spring:
  mqtt:
    username: 384819
    password: 5755367039510045632
    url: tcp://mqtt.heclouds.com:6002
  retrofit:
    url: http://127.0.0.1:8000

bortus: 
  job:
    accessToken: 
    admin:
      addresses: http://127.0.0.1:8000
    executor:
      appname: datapump-job-executor
      address: 
      ip: 127.0.0.1
      port: 9999
      logpath: /data/applogs/bortus/jobhandler
      logretentiondays: 30